### PR TITLE
Merge from my local project

### PR DESCRIPTION
**Pull request by alexax66**

### CODE REVIEW

**Comment by ericbsd** [comment]
Sorry, there was work already started for this. Also, we prefer GTK3 over QT.

If you want to help with something, make sure that it is not in progress at https://github.com/orgs/ghostbsd/projects/4.

**Comment by alexax66** [comment]
OK, very good!

**Comment by ericbsd** [comment]
You are welcome to add the translation if you want.

**Comment by alexax66** [comment]
Yes, I'm think  it will be useful for GhostBSD community

**Pull request closed without merging**
